version: '3.8'

services:
  app:
    build: .
    ports:
      - "3038:3038"
    volumes:
      - ./data:/app/data
      - ./chroma:/app/chroma
    environment:
      - OLLAMA_HOST=ollama
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    entrypoint: >
      /bin/sh -c "
        ollama serve &
        sleep 10 &&
        ollama pull qwen:0.5b &&
        wait
      "

volumes:
  ollama_data: 